# Generated by Django 4.1.7 on 2024-04-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zocialfi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('signal', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
