# Generated by Django 4.1.7 on 2024-04-12 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zocialfi', '0002_signals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signals',
            new_name='Signal',
        ),
    ]
